# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Routinus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Routinus
  pod 'SwiftLint', '0.45.0'
  pod 'SnapKit', '5.0.1'
  pod 'Kingfisher', '7.0'
end
